apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: angular-pvc
  namespace: ${namespace}
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi