apiVersion: v1
kind: Service
metadata:
  namespace: ${namespace}
  name: angular
  labels:
    app: angular
spec:
  selector:
    app: angular
  ports:
    - protocol: TCP
      port: 4500
      targetPort: 4500
  type: NodePort